import axios from 'axios';
import { DeliveryProvider, Digest } from './index.js';
import { logger } from '../../core/logger.js';

export class SlackDelivery implements DeliveryProvider {
  constructor(private webhookUrl: string) {}

  async send(digest: Digest): Promise<void> {
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `🚀 Alif AI Signal Digest - ${digest.metadata.date}`,
          emoji: true,
        },
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `Found *${digest.metadata.total_selected}* high-signal items out of *${digest.metadata.total_new_items}* new articles analyzed today.`,
        },
      },
      { type: 'divider' },
    ];

    for (const item of digest.items) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*<${item.url}|${item.title}>*\n_${item.category}_ • ${item.source} • Score: ${item.score}\n${item.summary || 'No summary available.'}`,
        },
      } as any);
    }

    blocks.push({
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: 'Generated by *Alif CLI* — Built by qarib.',
        },
      ],
    } as any);

    try {
      await axios.post(this.webhookUrl, { blocks });
    } catch (error) {
      logger.error(
        `[Slack] Failed to deliver ${digest.items.length} items:`,
        error instanceof Error ? error.message : String(error),
      );
      throw error;
    }
  }
}
